---
title: "How much does it cost to give birth in the United States?"
subtitle: "By Dan Snow"
format:
  html:
    toc: false
    embed-resources: true
    grid:
      body-width: 900px
execute:
  echo: false
---

```{r setup, message=FALSE}
library(arrow)
library(data.table)
library(dplyr)
library(forcats)
library(ggplot2)
library(ggrepel)
library(ggridges)
library(ggtext)
library(Hmisc)
library(scales)
library(sf)
library(stringr)
library(tigris)
library(tidyr)

# Necessary for fast/accurate map rendering
sf_use_s2(FALSE)
options(tigris_use_cache = TRUE)
```

```{r load_data, message=FALSE, warning=FALSE}
# Load data from ingest script
rates_df <- read_parquet("data/rates_clean.parquet")
zip_adj_df <- read_parquet("data/zip_adj_matrix.parquet")
census_regions <- readr::read_csv("data/us_census_regions.csv")

# Bounding box cuts off the Aleutian islands in Alaska
states_bbox <- c(xmin = -168, xmax = -65, ymin = 18.5, ymax = 72) %>%
  st_bbox(crs = 4326) %>%
  st_as_sfc() %>%
  st_transform(4269)
states_gdf <- tigris::states(cb = TRUE, year = 2023) %>%
  filter(str_sub(GEOID) <= "56") %>%
  select(geoid = GEOID, state = STUSPS, geometry) %>%
  st_intersection(states_bbox) %>%
  tigris::shift_geometry()
county_gdf <- tigris::counties(cb = TRUE, year = 2023) %>%
  select(geoid = GEOID, geometry) %>%
  st_intersection(states_bbox) %>%
  tigris::shift_geometry()
cbsa_gdf <- tigris::core_based_statistical_areas(cb = TRUE, year = 2023) %>%
  select(geoid = GEOID, cbsa_name = NAME, geometry) %>%
  st_intersection(states_bbox) %>%
  tigris::shift_geometry()
zcta_gdf <- tigris::zctas(cb = TRUE, year = 2020) %>%
  select(geoid = GEOID20, geometry) %>%
  st_intersection(states_bbox) %>%
  tigris::shift_geometry()
```

```{r rate_summary, message=FALSE}
# Merge CBSA names to rates data + add some missing bed counts pulled
# from CMS / the internet
rates_fil_df <- rates_df %>%
  left_join(
    cbsa_gdf %>% st_drop_geometry(),
    by = c("geoid_cbsa" = "geoid")
  ) %>%
  mutate(
    total_beds = case_when(
      provider_id == "1676" ~ 67,
      provider_id == "453" ~ 25,
      provider_id == "7916" ~ 15,
      provider_id == "7999" ~ 72,
      provider_id == "8000" ~ 36,
      .default = total_beds
    )
  ) %>%
  filter(
    # These are actually mislabeled ASCs and cancer centers
    !provider_id %in% c("2354", "7951", "7985", "7986", "7991")
  ) %>%
  # This billing code is different from the other DRGs to we're going to
  # exclude it in this case
  filter(billing_code != "768")

# Collapse plans to the provider-payer level, prioritizing PPO + HMO rates,
# then PPO only, then HMO only, then any other plan types (we want the highest
# utilization plans only, and this is a trick to get them)
provider_payer_df <- rates_fil_df %>%
  mutate(
    is_ppo = str_detect(payer_product_network, "PPO"),
    is_hmo = str_detect(payer_product_network, "HMO")
  ) %>%
  group_by(provider_id, billing_code_type, billing_code, payer_id) %>%
  summarise(
    across(
      # These don't vary within group, so it's fine to just take the first value
      # in order to preserve them
      c(
        provider_name, provider_npi, parent_payer_name, medicare_rate,
        hospital_type, total_beds, star_rating, state_market_share, cbsa_name,
        starts_with("geoid_"), starts_with("total_"), starts_with("median_hh_"),
        starts_with("pct_ins_")
      ),
      first
    ),
    agg_rate_provider_payer_type = case_when(
      any(is_ppo) & any(is_hmo) ~ "PPO/HMO",
      any(is_ppo) ~ "PPO",
      any(is_hmo) ~ "HMO",
      .default = "MIX"
    ),
    agg_rate_provider_payer_med = case_when(
      any(is_ppo) & any(is_hmo) ~ median(
        final_rate_amount[payer_product_network %in% c("PPO", "HMO")]
      ),
      any(is_ppo) ~ median(final_rate_amount[payer_product_network == "PPO"]),
      any(is_hmo) ~ median(final_rate_amount[payer_product_network == "HMO"]),
      .default = median(final_rate_amount)
    ),
    agg_rate_provider_payer_count = case_when(
      any(is_ppo) & any(is_hmo) ~ sum(
        payer_product_network %in% c("PPO", "HMO")
      ),
      any(is_ppo) ~ sum(payer_product_network == "PPO"),
      any(is_hmo) ~ sum(payer_product_network == "HMO"),
      .default = n()
    )
  ) %>%
  left_join(
    tigris::fips_codes %>%
      distinct(state, state_code),
    by = c("geoid_state" = "state_code")
  ) %>%
  left_join(
    census_regions,
    by = "state"
  )

# Collapse provider-plan-level rates to the provider level, weighting by number
# of covered lives / market share per payer (to downweight tiny payers)
providers_df <- provider_payer_df %>%
  group_by(provider_id, billing_code_type, billing_code) %>%
  summarise(
    across(-all_of(c(
      "payer_id", "parent_payer_name",
      "agg_rate_provider_payer_type",
      "agg_rate_provider_payer_count"
    )), first),
    agg_rate_provider_med = wtd.quantile(
      agg_rate_provider_payer_med, state_market_share, 0.5
    ),
    agg_rate_provider_count = sum(agg_rate_provider_payer_count)
  ) %>%
  mutate(
    severity_label = factor(case_when(
      billing_code %in% c("783", "786", "796", "805") ~ "w/ MCC",
      billing_code %in% c("784", "787", "797", "806") ~ "w/ CC",
      billing_code %in% c("785", "788", "798", "807") ~ "no CC/MCC"
    ), levels = c(
      "w/ MCC",
      "w/ CC",
      "no CC/MCC"
    )),
    billing_code_label = factor(case_when(
      billing_code %in% c("783", "784", "785") ~
        "Caesarean Section<br>w/ Steril.",
      billing_code %in% c("786", "787", "788") ~
        "Caesarean Section<br>no Steril.",
      billing_code %in% c("796", "797", "798") ~
        "Vaginal Delivery<br>w/ Steril./D&C",
      billing_code %in% c("805", "806", "807") ~
        "Vaginal Delivery<br>no Steril./D&C"
    ), levels = c(
      "Vaginal Delivery<br>no Steril./D&C",
      "Vaginal Delivery<br>w/ Steril./D&C",
      "Caesarean Section<br>no Steril.",
      "Caesarean Section<br>w/ Steril."
    ))
  ) %>%
  ungroup()
```

```{r price_by_drg, message=FALSE}
#| column: page
#| out-width: 100%
#| fig-width: 9
#| fig-height: 7

# Get the distribution of prices for each DRG, weighted by provider bed count
# and organized by delivery type and severity
price_by_drg_df <- providers_df %>%
  group_by(billing_code, billing_code_label, severity_label) %>%
  summarise(
    xmin = wtd.quantile(agg_rate_provider_med, total_beds, 0.10),
    lower = wtd.quantile(agg_rate_provider_med, total_beds, 0.25),
    median = wtd.quantile(agg_rate_provider_med, total_beds, 0.50),
    upper = wtd.quantile(agg_rate_provider_med, total_beds, 0.75),
    xmax = wtd.quantile(agg_rate_provider_med, total_beds, 0.90),
    drg_label = unique(paste0(
      billing_code_label, " ", severity_label
    )),
    count_label = paste0(
      "(", scales::label_comma()(sum(agg_rate_provider_count)), ")"
    )
  )

# Fancy pants boxplot of cost and count by delivery DRG
price_by_drg_df %>%
  ggplot() +
  geom_boxplot(
    aes(
      xmin = xmin, xlower = lower, xmiddle = median,
      xupper = upper, xmax = xmax, y = NA
    ),
    width = 0.5,
    outliers = FALSE,
    stat = "identity",
    position = position_nudge(y = -0.1)
  ) +
  annotate(
    "rect",
    xmin = -Inf, xmax = 35000, ymin = 1.45, ymax = 1.8,
    fill = "grey80"
  ) +
  annotate(
    "rect",
    xmin = -Inf, xmax = 11500, ymin = 1.45, ymax = 1.8,
    fill = "grey75"
  ) +
  annotate(
    "rect",
    xmin = 25500, xmax = Inf, ymin = -Inf, ymax = 0.625,
    fill = "#e0ebea"
  ) +
  geom_richtext(
    aes(label = paste0("**", billing_code, "**")),
    x = 5500,
    y = 1.6,
    label.colour = "transparent",
    fill = "transparent",
    text.color = "grey30",
    size = 5,
    hjust = 0
  ) +
  geom_richtext(
    aes(label = drg_label),
    x = 12000,
    y = 1.62,
    label.colour = "transparent",
    fill = "transparent",
    text.color = "grey10",
    size = 3,
    hjust = 0
  ) +
  geom_richtext(
    aes(label = count_label),
    x = 32200,
    y = 0.5,
    label.colour = "transparent",
    fill = "transparent",
    text.color = "grey40",
    size = 2.8,
    hjust = 1
  ) +
  scale_x_continuous(
    labels = scales::label_dollar(scale = 1 / 1000, suffix = "K"),
    n.breaks = 5,
    expand = c(0.1, 0)
  ) +
  coord_cartesian(xlim = c(7500, 30000)) +
  facet_grid(
    cols = vars(billing_code_label),
    rows = vars(severity_label),
    switch = "both"
  ) +
  labs(
    title = "The cost of giving birth increases with complexity",
    x = paste0(
      "<span style='color:grey60;'>Delivery price</span>",
      "<br><span style='font-size:20px'>",
      "More complex delivery types ",
      "<span style='font-size:36px'>→</span></span>"
    ),
    y = paste0(
      "**More complications and comorbidities ",
      "<span style='font-size:36px'>→</span>**"
    ),
    subtitle = paste0(
      "Complicated care (a C-section with comorbidities) costs ",
      "roughly double an uncomplicated vaginal birth"
    ),
    caption = paste0(
      "Counts (in parenthesis) are the number of unique *rates* per ",
      "combined delivery type and level of complication<br>",
      "Based on ",
      providers_df %>%
        pull(agg_rate_provider_count) %>%
        sum() %>%
        scales::label_comma()(),
      " negotiated commmercial insurance rates from Turquoise Health,",
      " covering ",
      providers_df %>%
        distinct(provider_id) %>%
        nrow() %>%
        scales::label_comma()(),
      " providers<br>",
      "Boxes show the 10th, 25th, 50th, 75th, and 90th percentiles of ",
      "provider-level delivery prices, weighted by bed count"
    )
  ) +
  theme(
    plot.title = element_text(size = 18, face = "bold", margin = margin(b = 6)),
    plot.subtitle = element_markdown(size = 13, margin = margin(b = 16)),
    plot.margin = margin(r = 10, t = 6, b = 6, l = 6),
    axis.text.y = element_markdown(
      size = 14,
      margin = margin(r = 4),
      lineheight = 1.25,
      color = "grey40"
    ),
    axis.title.x = element_markdown(
      margin = margin(t = 4),
      size = 14,
      face = "bold",
      color = "grey40",
      linewidth = 1.2
    ),
    axis.text.x = element_text(size = 12, angle = -45, hjust = 0),
    axis.ticks.y = element_blank(),
    axis.title.y = element_markdown(
      size = 15,
      color = "grey40",
      margin = margin(r = 2)
    ),
    panel.grid.major.y = element_blank(),
    panel.grid.minor.y = element_blank(),
    panel.background = element_rect(fill = "#e0ebea"),
    strip.background = element_blank(),
    strip.text = element_blank(),
    plot.caption = element_markdown(
      size = 10,
      lineheight = 1.1,
      margin = margin(t = 16, r = -2)
    )
  )
```

```{r price_by_medicare, message=FALSE}
#| column: page
#| out-width: 100%
#| fig-width: 9
#| fig-height: 7

# Same plot as before, but this time for rate as a percent of Medicare
providers_df %>%
  mutate(provider_med = median(agg_rate_provider_med), .by = provider_id) %>%
  mutate(price_ntile = ntile(provider_med, n = 10), .by = NULL) %>%
  group_by(billing_code_label, severity_label, price_ntile) %>%
  summarise(
    med = wtd.quantile(agg_rate_provider_med / medicare_rate, total_beds, 0.50)
  ) %>%
ggplot() +
  geom_point(
    aes(
      x = price_ntile,
      y = med,
      color = severity_label,
      group = severity_label
    )
  ) +
  geom_line(
    aes(
      x = price_ntile,
      y = med,
      color = severity_label,
      group = severity_label
    )
  ) +
  scale_x_continuous(
    n.breaks = 10
  ) +
  scale_y_continuous(
    labels = scales::label_percent(),
    n.breaks = 6,
    expand = c(0.1, 0)
  ) +
  guides(color = guide_legend(title = "Severity", reverse = TRUE)) +
  facet_wrap(vars(billing_code_label), nrow = 2, dir = "v") +
  labs(
    title = paste0(
      "Delivery prices increase non-linearly"
    ),
    subtitle = paste0(
      "The most expensive providers charge signficantly more than their",
      " slightly less expensive peers"
    ),
    x = "Provider decile",
    y = "Median percent of Medicare rate",
    caption = paste0(
      "Deciles are based on the median price of each provider's combined ",
      "MS-DRG rates for delivery<br>",
      "Lines show provider-level delivery prices divided by their respective ",
      "Medicare rates and weighted by",
      " bed count<br>",
      "Based on ",
      providers_df %>%
        pull(agg_rate_provider_count) %>%
        sum() %>%
        scales::label_comma()(),
      " negotiated commmercial insurance rates from Turquoise Health,",
      " covering ",
      providers_df %>%
        distinct(provider_id) %>%
        nrow() %>%
        scales::label_comma()(),
      " providers<br>"
    )
  ) +
  theme(
    plot.title = element_text(size = 18, face = "bold", margin = margin(b = 6)),
    plot.subtitle = element_markdown(
      size = 13,
      margin = margin(b = 16),
      lineheight = 1.1
    ),
    plot.margin = margin(r = 6, t = 6, l = 6),
    legend.title = element_text(
      size = 14,
      face = "bold",
      color = "grey30",
      margin = margin(b = 8)
    ),
    legend.text = element_text(size = 12, color = "grey40"),
    legend.key.spacing.y = unit(0.25, "cm"),
    axis.text.x = element_text(size = 12, color = "grey40"),
    axis.text.y = element_markdown(
      size = 14,
      margin = margin(r = 4),
      lineheight = 1.25,
      color = "grey40"
    ),
    axis.title.x = element_text(
      margin = margin(t = 4),
      size = 14,
      face = "bold",
      color = "grey40"
    ),
    axis.title.y = element_markdown(
      size = 15,
      color = "grey40",
      margin = margin(r = 4),
      face = "bold"
    ),
    panel.grid.minor.x = element_blank(),
    panel.grid.minor.y = element_blank(),
    panel.background = element_rect(fill = "#e0ebea"),
    strip.text = element_markdown(size = 12),
    plot.caption = element_markdown(
      size = 10,
      lineheight = 1.1,
      margin = margin(t = 16, r = -104)
    )
  )
```

```{r top_n_pop_plot, message=FALSE}
#| column: page
#| out-width: 100%
#| fig-width: 12
#| fig-height: 14

# Main DRGs to visualize and their respective, ordered labels
billing_code_values <- c("807", "788", "805")
billing_code_labels <- c(
  "**807:** Vaginal Delivery (no MCC)",
  "**788:** Cesarean Section",
  "**805:** Vaginal Delivery (w/ MCC)"
)

# Get the median rate for each code for all providers. Used later to draw
# vlines on plots
us_code_price_df <- providers_df %>%
  filter(billing_code %in% billing_code_values) %>%
  group_by(billing_code) %>%
  summarise(
    med_rate = wtd.quantile(agg_rate_provider_med, total_beds, 0.50)
  ) %>%
  mutate(
    billing_code_label = factor(
      billing_code,
      levels = billing_code_values,
      labels = billing_code_labels
    )
  )

# Get the top N largest CBSAs by population and the top N most expensive
top_n_pop_df <- providers_df %>%
  group_by(cbsa_name) %>%
  summarise(cbsa_pop = first(total_pop_cbsa)) %>%
  slice_max(cbsa_pop, n = 30)

# Create fancy ggplot labels and boxplots for the top N CBSAs
providers_df %>%
  group_by(cbsa_name) %>%
  filter(
    cbsa_name %in% top_n_pop_df$cbsa_name,
    billing_code %in% billing_code_values
  ) %>%
  mutate(cbsa_name = factor(cbsa_name, levels = top_n_pop_df$cbsa_name)) %>%
  arrange(cbsa_name) %>%
  mutate(
    cbsa_label = fct_relabel(cbsa_name, \(x) {
      unique(paste0(
        "**", x, "**<br>",
        "<sup>Population: ", purrr::map_chr(
          total_pop_cbsa,
          scales::label_number(scale_cut = cut_short_scale())
        ),
        " | ",
        "Providers: ", n_distinct(provider_id), "</sup>"
      ))
    }),
    billing_code_label = factor(
      billing_code,
      levels = billing_code_values,
      labels = billing_code_labels
    )
  ) %>%
  group_by(cbsa_label, billing_code_label) %>%
  mutate(
    lower = wtd.quantile(agg_rate_provider_med, total_beds, 0.25),
    median = wtd.quantile(agg_rate_provider_med, total_beds, 0.50),
    upper = wtd.quantile(agg_rate_provider_med, total_beds, 0.75)
  ) %>%
  group_by(billing_code_label) %>%
  mutate(cbsa_label = fct_reorder(cbsa_label, median, .desc = FALSE)) %>%
  ggplot() +
  ggridges::geom_density_ridges(
    aes(
      x = agg_rate_provider_med,
      y = cbsa_label,
      group = cbsa_label,
      weight = total_beds
    ),
    position = position_nudge(y = -0.1),
    quantile_lines = TRUE,
    quantiles = 2,
    quantile_fun = Hmisc::wtd.quantile
  ) +
  geom_vline(
    data = us_code_price_df,
    aes(xintercept = med_rate, group = billing_code_label),
    color = "darkred",
    linetype = "dashed"
  ) +
  scale_x_continuous(
    name = "Delivery Price",
    labels = scales::label_dollar(scale = 1 / 1000, suffix = "K"),
    n.breaks = 6,
    expand = c(0, 0)
  ) +
  facet_wrap(vars(billing_code_label)) +
  labs(
    title = paste0(
      "New York City is the most expensive large U.S. ",
      "market for childbirth"
    ),
    subtitle = paste0(
      "Other areas are closer to the ",
      "**<span style='color:darkred'>national median price</span>** ",
      "for each delivery type"
    ),
    caption = paste0(
      "Delivery types include the most common delivery-related MS-DRG codes\n",
      "Based on ",
      providers_df %>%
        filter(
          cbsa_name %in% top_n_pop_df$cbsa_name,
          billing_code %in% billing_code_values
        ) %>%
        pull(agg_rate_provider_count) %>%
        sum() %>%
        scales::label_comma()(),
      " negotiated commmercial insurance rates from",
      " Turquoise Health, covering ",
      providers_df %>%
        filter(
          cbsa_name %in% top_n_pop_df$cbsa_name,
          billing_code %in% billing_code_values
        ) %>%
        distinct(provider_id) %>%
        nrow() %>%
        scales::label_comma()(),
      " providers\n",
      "Distributions show provider-level delivery prices, weighted by",
      " bed count. Line represents the median\n",
      "Markets are defined as the top 30 most populous 2023 Census ",
      "Core-Based Statistical Areas (CBSAs)"
    )
  ) +
  coord_cartesian(xlim = c(3000, 37000)) +
  theme(
    plot.title = element_text(
      size = 20,
      face = "bold",
      margin = margin(b = 6, l = -150)
    ),
    plot.subtitle = element_markdown(
      size = 17,
      margin = margin(b = 16, l = -110)
    ),
    axis.title.y = element_blank(),
    axis.text.y = element_markdown(
      lineheight = 1.25,
      size = 10,
      margin = margin(t = 4)
    ),
    axis.title.x = element_text(
      margin = margin(t = 10),
      size = 15,
      face = "bold",
      color = "grey30"
    ),
    axis.text.x = element_text(size = 12),
    axis.ticks.y = element_blank(),
    panel.grid.major.y = element_blank(),
    panel.grid.minor.y = element_blank(),
    panel.background = element_rect(fill = "#e0ebea"),
    strip.background = element_rect(fill = "grey80"),
    strip.text = element_markdown(
      size = 13.5,
      margin = margin(b = 4, t = 6),
      color = "grey20"
    ),
    plot.caption = element_text(
      size = 11,
      lineheight = 1.1,
      margin = margin(t = 20)
    )
  )
```

```{r state_map_plot, message=FALSE, warning=FALSE, results='hide'}
#| column: page
#| out-width: 100%
#| fig-width: 12
#| fig-height: 9

states_summ_df <- providers_df %>%
  filter(billing_code == "807") %>%
  group_by(geoid_state, state) %>%
  filter(!all(is.na(agg_rate_provider_med))) %>%
  summarise(
    pct_ins_pri_state = first(pct_ins_pri_state),
    pct_ins_pub_state = first(pct_ins_pub_state),
    med_rate = wtd.quantile(agg_rate_provider_med, total_beds, 0.50),
    med_income = first(median_hh_income_state),
    cnt = n()
  ) %>%
  mutate(
    rate_label = cut(
      med_rate,
      breaks = c(0, 7000, 10000, 13000, 16000, Inf),
      labels = c(
        "< $7K", "$7-10K", "$10-13K",
        "$13-16K", "> $16K"
      )
    ),
    rate_label = fct_rev(rate_label)
  )

# Create a binned, state-level map of median rates
states_gdf %>%
  left_join(states_summ_df, by = c("geoid" = "geoid_state")) %>%
  ggplot() +
  geom_sf(
    aes(fill = rate_label),
    color = "grey30",
    linewidth = 0.7,
    show.legend = TRUE
  ) +
  scale_fill_brewer(
    name = "Wtd. Median\nDelivery Price",
    palette = "BuPu",
    direction = -1,
    na.value = "grey80",
    drop = FALSE
  ) +
  coord_sf(expand = FALSE) +
  guides(fill = guide_legend(override.aes = list(color = "grey20"))) +
  labs(
    title = paste0(
      "Alaska, New York, and New Jersey have the ",
      "highest delivery prices nationwide"
    ),
    subtitle = paste0(
      "Compared to the national median of ",
      us_code_price_df %>%
        filter(billing_code == "807") %>%
        pull(med_rate) %>%
        round() %>%
        scales::label_currency()(),
      " for uncomplicated vaginal delivery"
    ),
    caption = paste0(
      "Includes only vaginal deliveries without sterilization ",
      "or complications (MS-DRG 807)\n",
      "Based on ",
      providers_df %>%
        filter(billing_code == "807") %>%
        pull(agg_rate_provider_count) %>%
        sum() %>%
        scales::label_comma()(),
      " negotiated commmercial insurance rates from",
      " Turquoise Health, covering ",
      providers_df %>%
        filter(billing_code == "807") %>%
        distinct(provider_id) %>%
        nrow() %>%
        scales::label_comma()(),
      " providers\n",
      "Rates are aggregated to the provider level, then to ",
      "the state level (weighted by provider bed count)\n"
    )
  ) +
  theme(
    panel.grid = element_blank(),
    panel.background = element_blank(),
    axis.text = element_blank(),
    axis.ticks = element_blank(),
    legend.key.spacing.y = unit(0.15, "cm"),
    legend.title = element_text(
      size = 15,
      face = "bold",
      margin = margin(b = 10)
    ),
    legend.margin = margin(t = 80, l = -50),
    legend.key.size = unit(0.75, "cm"),
    legend.text = element_text(size = 12),
    plot.title = element_text(
      size = 20,
      face = "bold",
      margin = margin(b = -44)
    ),
    plot.subtitle = element_markdown(
      size = 17,
      margin = margin(t = 50, b = 24)
    ),
    plot.caption = element_text(
      size = 11,
      lineheight = 1.1,
      margin = margin(r = -60, t = 10)
    )
  )
```

```{r zip_map_plot, message=FALSE, warning=FALSE, results='hide'}
#| column: page
#| out-width: 100%
#| fig-width: 12
#| fig-height: 9

# Logistic distance decay. A hospital that's an hour away has half the weight
# of one that's 0 minutes away. Probably should be a different (closer) midpoint
# for cities, but it's hard to get ZIP code urban/rural classifications
decay_function <- function(x) {
  midpoint <- 3600
  steepness <- 0.001
  weight <- 1 / (1 + exp(steepness * (x - midpoint)))
  weight
}

# Merge providers using data.table, getting the median rate of providers that
# are within 3 hours of the origin ZIP code. Weight each provider by the number
# of beds and the distance from the ZIP
setDT(zip_adj_df)
setDT(providers_df)
zcta_summ_df <- merge(
  zip_adj_df,
  providers_df[
    billing_code == "807",
    c("provider_id", "agg_rate_provider_med", "total_beds")
  ],
  by = "provider_id",
  all.x = TRUE,
  allow.cartesian = TRUE
)[!is.na(agg_rate_provider_med), ][, .(
  med_rate = wtd.quantile(
    agg_rate_provider_med,
    total_beds * decay_function(duration_sec),
    0.50,
    na.rm = TRUE
  ),
  med_duration = median(duration_sec),
  n = .N
), by = origin_id]

# Plot all ZIP codes with the median rate of providers within 3 hours
zcta_gdf %>%
  left_join(zcta_summ_df, by = c("geoid" = "origin_id")) %>%
  mutate(
    rate_label = cut(
      med_rate,
      breaks = c(0, 7000, 10000, 13000, 16000, Inf),
      labels = c(
        "< $7K", "$7-10K", "$10-13K",
        "$13-16K", "> $16K"
      )
    ),
    rate_label = fct_rev(rate_label)
  ) %>%
  ggplot() +
  geom_sf(data = states_gdf, fill = "grey80", color = "grey80") +
  geom_sf(aes(fill = rate_label, color = rate_label)) +
  geom_sf(
    data = states_gdf,
    fill = "transparent",
    color = "grey30",
    linewidth = 0.7
  ) +
  scale_fill_brewer(palette = "BuPu", direction = -1, na.value = "grey80") +
  scale_color_brewer(palette = "BuPu", direction = -1, na.value = "grey80") +
  coord_sf(expand = FALSE) +
  guides(fill = guide_legend(override.aes = list(color = "grey20"))) +
  labs(
    fill = "Wtd. Median\nDelivery Price",
    color = "Wtd. Median\nDelivery Price",
    title = paste0(
      "New York and California have the most expensive",
      " ZIP codes for delivery"
    ),
    subtitle = paste0(
      "High prices in rural areas typically indicate a low number of ",
      "high-priced providers and/or commercial cross-subsidization"
    ),
    caption = paste0(
      "Includes only vaginal deliveries without sterilization ",
      "or complications (MS-DRG 807)\n",
      "Based on ",
      providers_df %>%
        filter(billing_code == "807") %>%
        pull(agg_rate_provider_count) %>%
        sum() %>%
        scales::label_comma()(),
      " negotiated commmercial insurance rates from",
      " Turquoise Health, covering ",
      providers_df %>%
        filter(billing_code == "807") %>%
        distinct(provider_id) %>%
        nrow() %>%
        scales::label_comma()(),
      " providers\n",
      "Each ZIP code's price is the weighted (by bed count and distance) ",
      "median of providers within a ",
      "3 hour drive. Grey ZIP codes lack population or providers\n"
    )
  ) +
  theme(
    panel.grid = element_blank(),
    panel.background = element_blank(),
    axis.text = element_blank(),
    axis.ticks = element_blank(),
    legend.key.spacing.y = unit(0.15, "cm"),
    legend.title = element_text(
      size = 15,
      face = "bold",
      margin = margin(b = 10)
    ),
    legend.margin = margin(t = 80, l = -50),
    legend.key.size = unit(0.75, "cm"),
    legend.text = element_text(size = 12),
    plot.title = element_text(
      size = 20,
      face = "bold",
      margin = margin(b = 6)
    ),
    plot.subtitle = element_markdown(size = 15, margin = margin(b = 14)),
    plot.caption = element_text(
      size = 10,
      lineheight = 1.1,
      margin = margin(t = 10, r = -60)
    )
  )
```

```{r price_vs_fertility, message=FALSE}
#| column: page
#| out-width: 100%
#| fig-width: 8
#| fig-height: 6

cdc_fertility <- readr::read_csv("data/cdc_fertility.csv") %>%
  select(year = YEAR, state = STATE, fertility_rate = `FERTILITY RATE`) %>%
  filter(year == 2022) %>%
  mutate(state = case_match(
    state,
    "District of Columbia" ~ "DC",
    .default = state
  ))

states_summ_df %>%
  left_join(cdc_fertility, by = "state") %>%
  ggplot(aes(x = med_rate, y = fertility_rate)) +
  geom_point() +
  geom_text_repel(aes(label = state), color = "grey70") +
  geom_smooth(
    method = "lm",
    color = "darkred",
    se = FALSE,
    alpha = 0.5
  ) +
  scale_y_continuous(
    name = "Fertility Rate<sup>1</sup>",
    n.breaks = 8,
    expand = c(0.02, 0)
  ) +
  scale_x_continuous(
    name = "Delivery Price",
    labels = scales::label_dollar(scale = 1 / 1000, suffix = "K"),
    n.breaks = 6,
    expand = c(0.02, 0)
  ) +
  labs(
    title = "States with high delivery costs have lower fertility rates",
    caption = paste0(
      "<sup>1</sup> Rate per 1,000 women aged 15–44, ",
      "based on 2022 CDC/NCHS data<br>",
      "Includes only vaginal deliveries without sterilization ",
      "or complications (MS-DRG 807)<br>",
      "Based on ",
      providers_df %>%
        filter(billing_code == "807") %>%
        pull(agg_rate_provider_count) %>%
        sum() %>%
        scales::label_comma()(),
      " negotiated commmercial insurance rates from",
      " Turquoise Health, covering ",
      providers_df %>%
        filter(billing_code == "807") %>%
        distinct(provider_id) %>%
        nrow() %>%
        scales::label_comma()(),
      " providers<br>",
      "Rates are aggregated to the provider level, then to ",
      "the state level (weighted by provider bed count)\n"
    )
  ) +
  theme_minimal() +
  theme(
    plot.title = element_text(
      size = 18,
      face = "bold",
      margin = margin(b = 10)
    ),
    plot.subtitle = element_markdown(size = 15),
    axis.title.y = element_markdown(
      size = 13,
      face = "bold",
      margin = margin(r = 10),
      color = "grey40"
    ),
    axis.text.y = element_markdown(size = 11),
    axis.title.x = element_text(
      margin = margin(t = 10),
      size = 13,
      face = "bold",
      color = "grey40"
    ),
    axis.text.x = element_text(size = 11),
    strip.background = element_blank(),
    plot.caption = element_markdown(
      size = 10,
      lineheight = 1.1,
      margin = margin(t = 20)
    )
  )
```

```{r buca_dist, message=FALSE}
#| column: page
#| out-width: 100%
#| fig-width: 8
#| fig-height: 7

buca_df <- provider_payer_df %>%
  filter(
    billing_code == "807",
    parent_payer_name %in% c(
      "Blue Cross Blue Shield Association",
      "United Healthcare",
      "Cigna",
      "Aetna"
    )
  ) %>%
  mutate(
    payer_label = case_match(
      parent_payer_name,
      "Blue Cross Blue Shield Association" ~ "BCBS",
      "United Healthcare" ~ "UHC",
      .default = parent_payer_name
    ),
    payer_label = factor(
      payer_label,
      levels = c("BCBS", "UHC", "Cigna", "Aetna")
    ),
    region_label = factor(
      region,
      levels = c("West", "Midwest", "South", "Northeast")
    )
  ) %>%
  group_by(payer_label) %>%
  mutate(
    payer_label = fct_relabel(payer_label, \(x) {
      unique(paste0(
        "**", x, "**<br>",
        "<sup>(", purrr::map_chr(
          n(),
          scales::label_comma()
        ), ")</sup>"
      ))
    })
  ) %>%
  group_by(region_label) %>%
  mutate(
    region_label = fct_relabel(region_label, \(x) {
      unique(paste0(
        "**", x, "**<br>",
        "<sup>(", purrr::map_chr(
          n(),
          scales::label_comma()
        ), ")</sup>"
      ))
    }),
    region_med = wtd.quantile(agg_rate_provider_payer_med, total_beds, 0.50)
  ) %>%
  ungroup()

buca_df %>%
  group_by(payer_label, region_label) %>%
  summarise(
    region = first(region),
    region_med = first(region_med),
    xmin = wtd.quantile(agg_rate_provider_payer_med, total_beds, 0.10),
    lower = wtd.quantile(agg_rate_provider_payer_med, total_beds, 0.25),
    median = wtd.quantile(agg_rate_provider_payer_med, total_beds, 0.50),
    upper = wtd.quantile(agg_rate_provider_payer_med, total_beds, 0.75),
    xmax = wtd.quantile(agg_rate_provider_payer_med, total_beds, 0.90),
    count = paste0("(", purrr::map_chr(n(), scales::label_comma()), ")")
  ) %>%
  ggplot() +
  geom_vline(
    aes(xintercept = region_med),
    color = "darkred",
    linetype = "dashed"
  ) +
  geom_boxplot(
    aes(
      xmin = xmin, xlower = lower, xmiddle = median,
      xupper = upper, xmax = xmax, y = NA
    ),
    width = 0.5,
    outliers = FALSE,
    stat = "identity"
  ) +
  annotate(
    "rect",
    xmin = 16500, xmax = Inf, ymin = 0.4, ymax = 0.65,
    fill = "#e0ebea"
  ) +
  geom_text(
    aes(x = 18000, y = NA, label = count),
    nudge_y = -0.46,
    color = "grey40",
    size = 2.8
  ) +
  scale_x_continuous(
    name = "Delivery Price",
    labels = scales::label_dollar(scale = 1 / 1000, suffix = "K"),
    n.breaks = 5,
    expand = c(0.1, 0)
  ) +
  facet_grid(
    cols = vars(region_label),
    rows = vars(payer_label),
    switch = "y"
  ) +
  coord_cartesian(xlim = c(5500, 18500)) +
  labs(
    title = "Major insurance companies have similar delivery prices",
    subtitle = paste0(
      "Across U.S. regions, large payers stay close to the ",
      "**<span style='color:darkred'>regional median price</span>** ",
      "for delivery"
    ),
    caption = paste0(
      "Includes only vaginal deliveries without sterilization ",
      "or complications (MS-DRG 807)<br>",
      "Counts (in parenthesis) are the number of unique",
      " *rates* per U.S. Census ",
      "region, payer, or combination thereof<br>",
      "Based on ",
      buca_df %>%
        pull(agg_rate_provider_payer_count) %>%
        sum() %>%
        scales::label_comma()(),
      " negotiated commmercial insurance rates from",
      " Turquoise Health, covering ",
      buca_df %>%
        distinct(provider_id) %>%
        nrow() %>%
        scales::label_comma()(),
      " providers<br>",
      "Boxes show the 10th, 25th, 50th, 75th, and 90th percentiles of ",
      "provider-level delivery prices, weighted by bed count"
    )
  ) +
  theme(
    plot.title = element_text(
      size = 18,
      face = "bold",
      margin = margin(b = 6, l = -10)
    ),
    plot.subtitle = element_markdown(
      size = 13,
      margin = margin(b = 24, l = -20)
    ),
    axis.title.y = element_blank(),
    axis.text.y = element_markdown(
      size = 14, margin = margin(r = 4),
      lineheight = 1.25,
      color = "grey40"
    ),
    axis.title.x = element_text(
      margin = margin(t = 10),
      size = 14,
      face = "bold",
      color = "grey40"
    ),
    axis.text.x = element_text(size = 12, angle = -45, hjust = 0),
    axis.ticks.y = element_blank(),
    panel.grid.major.y = element_blank(),
    panel.grid.minor.y = element_blank(),
    panel.background = element_rect(fill = "#e0ebea"),
    strip.background = element_blank(),
    strip.text = element_markdown(
      size = 14,
      margin = margin(b = 2),
      lineheight = 1.25,
      color = "grey40"
    ),
    strip.text.y.left = element_markdown(
      angle = 0,
      margin = margin(r = 6),
      color = "grey40",
      hjust = 1
    ),
    plot.caption = element_markdown(
      size = 10,
      lineheight = 1.1,
      margin = margin(t = 20)
    )
  )
```

```{r}
providers_df %>%
  filter(billing_code == "807") %>%
  group_by(region, star_rating) %>%
  filter(!all(is.na(agg_rate_provider_med))) %>%
  summarise(
    xmin = wtd.quantile(agg_rate_provider_payer_med, total_beds, 0.10),
    lower = wtd.quantile(agg_rate_provider_payer_med, total_beds, 0.25),
    median = wtd.quantile(agg_rate_provider_payer_med, total_beds, 0.50),
    upper = wtd.quantile(agg_rate_provider_payer_med, total_beds, 0.75),
    xmax = wtd.quantile(agg_rate_provider_payer_med, total_beds, 0.90),
    cnt = n()
  ) %>%
ggplot() +
  geom_boxplot(
    aes(
      xmin = xmin, xlower = lower, xmiddle = median,
      xupper = upper, xmax = xmax, y = NA
    ),
    width = 0.5,
    outliers = FALSE,
    stat = "identity"
  ) +
  facet_grid(
    cols = vars(region),
    rows = vars(star_rating),
    scales = "free_x"
  )
  
```

