on:
  pull_request:
  push:
    branches: [main, master]

name: pre-commit

env:
  PYTHONUNBUFFERED: "1"

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-suffix: "pre-commit"

      - name: Install pre-commit
        shell: bash
        run: |
          uv python install
          uv venv
          uv pip install pre-commit

      - name: Cache pre-commit environment
        uses: actions/cache@v4
        with:
          path: ~/.cache/pre-commit
          key: pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}

      - name: Run pre-commit
        shell: bash
        run: uv run pre-commit run --show-diff-on-failure --color=always --all-files
