SELECT
    roid,
    state,
    county,
    zip_code,
    cbsa,
    cbsa_name,
    city,
    hq_latitude,
    hq_longitude,
    payer_name,
    network_id,
    network_name,
    payer_network_name,
    network_type,
    network_class,
    health_system_id,
    health_system_name,
    provider_id,
    provider_name,
    taxonomy_grouping,
    provider_type,
    cmi,
    npi,
    total_beds,
    bill_type,
    billing_code_type,
    billing_code,
    billing_code_full,
    canonical_rate_original_billing_codes,
    canonical_rate_original_billing_code_type,
    service_description,
    service_line,
    therapeutic_area,
    asp_payment_limit,
    medicare_rate,
    medicare_pricing_type,
    medicare_reference_source,
    state_avg_medicare_rate,
    discounted_cash_rate,
    canonical_gross_charge,
    canonical_gross_charge_type,
    canonical_gross_charge_source,
    canonical_rate_gross_charge_original_billing_codes,
    canonical_rate_gross_charge_original_billing_code_type,
    canonical_rate,
    canonical_rate_source,
    canonical_rate_type,
    canonical_contract_methodology,
    canonical_rate_category,
    canonical_rate_class,
    canonical_imputation_method,
    canonical_transformation_method,
    canonical_crosswalk_method,
    canonical_rate_percent_of_medicare,
    canonical_rate_percent_of_state_avg_medicare,
    canonical_rate_percent_of_list,
    canonical_rate_validation_method,
    canonical_rate_score,
    canonical_rate_subversion,
    best_payer_rate,
    best_payer_rate_score,
    best_payer_rate_validation_score,
    best_payer_rate_type,
    best_hospital_rate,
    best_hospital_rate_score,
    best_hospital_rate_validation_score,
    best_hospital_rate_type,
    komodo_gross_charge_provider,
    mrf_gross_charge_provider,
    komodo_gross_charge_cbsa_median,
    mrf_gross_charge_cbsa_median,
    mrf_gross_charge_state_median,
    gross_charge_cbsa_provider_adjustment,
    payer_file_hash,
    payer_last_updated_on,
    hospital_filename,
    hospital_ingested_on,
    canonical_method_params,
    canonical_method_formula,
    payer_id
FROM tq_dev.internal_dev_csong_cld_v2_0_1.prod_combined_abridged
WHERE taxonomy_grouping = 'Hospitals'
    AND canonical_rate IS NOT NULL
    AND billing_code_type = 'MS-DRG'
    AND billing_code = '807'
    AND LOWER(payer_network_name) LIKE '%blue%'
    AND network_type = 'PPO'
    AND state = 'CA'
    AND provider_name = 'Memorial Hospital Los Banos'
